stages:
  - install
  - lint
  - test
  - coverage
  
image: node:10.15.0-alpine

cache:
  key: "$CI_BUILD_REF_NAME"
  paths:
  - node_modules/

before_script:
  - npm set progress=false
  - apk add --no-cache git openssh-client
  - git submodule sync --recursive
  - git submodule update --init --recursive --depth 100

##################
#### INSTALL #####
##################

install:
  stage: install
  tags:
    - ecosystem-etagi
  script:
    - npm set //registry.npmjs.org/:_authToken=758021e9-1f07-4123-bac0-09ddefc64c67
    - npm install
    - npm install
  only:
  - merge_requests

##################
###### LINT ######
##################

lint:
  stage: lint
  tags:
    - ecosystem-etagi
  script:
    - npm run lint
  only:
  - merge_requests


##################
###### TEST ######
##################
 
test:
  stage: test
  tags:
    - ecosystem-etagi
  script:
    - npm test
  only:
  - merge_requests
  
##################
###### TEST ######
##################
 
coverage:
  stage: coverage
  tags:
    - ecosystem-etagi
  script:
    - npm run coverage 
  only:
  - merge_requests


