openapi: 3.0.1
info:
  title: Users service
  version: 1.0.0
servers:
  - url: http://localhost:{port}
    description: The production API server
    variables:
      port:
        enum:
          - '8085'
          - '443'
        default: '8085'
tags:
  - name: Users
    description: Everything about users
paths:
  /users:
    get:
      tags:
        - Users
      summary: Поиск пользователей
      operationId: searchUsers
      parameters:
        - name: id
          in: query
          schema:
            type: integer
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
      x-swagger-router-controller: usersController
    post:
      tags:
        - Users
      summary: Создание пользователя
      operationId: createUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        201:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        405:
          description: Invalid input
      x-swagger-router-controller: usersController
  /users/{userId}:
    parameters:
      - name: userId
        in: path
        required: true
        description: Id of user
        schema:
          type: integer
    get:
      tags:
        - Users
      summary: Получение пользователя по идентификатору
      operationId: getUser
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
      x-swagger-router-controller: usersController
    post:
      tags:
        - Users
      summary: Обновление пользователя
      operationId: updateUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserData'
      responses:
        200:
          description: Success
      x-swagger-router-controller: usersController
    delete:
      tags:
        - Users
      summary: Удаление пользователя по идентификатору
      operationId: deleteUser
      responses:
        200:
          description: Success
      x-swagger-router-controller: usersController
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int32
        accountId:
          type: integer
          format: int32
        lastName:
          type: string
        firstName:
          type: string
        middleName:
          type: string
    UserData:
      type: object
      properties:
        lastName:
          type: string
        firstName:
          type: string
        middleName:
          type: string
        login:
          type: string
        password:
          type: string
  responses:
    200:
      description: Success
    201:
      description: Created
    404:
      description: Not found